version: '3'
services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 7.4.33
    container_name: laravel_container
    ports:
      - 80:80
    volumes:
      - ./Cnpm_nhom5_TuoiNuocThongMinh:/var/www/html
    working_dir: /var/www/html
    
    version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_image
    container_name: laravel_container
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_DATABASE: db_iot
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:

